### ISSUE TITLE
Every call to `fnm env` creates a new symlink in ~/.local/state/fnm_multishells/

### ISSUE THREAD

**Issue by simonwhitaker** [Schniz/fnm#1157] opened 2024-06-02 10:09 UTC
MacOS Sonoma 14.5, fnm 1.37.0

Looks like this started happening around 30 May 2024. I run `brew upgrade` pretty often, so I suspect this was 
introduced in either 1.36.0 (released 28 May) or 1.37.0 (released 30 May).

## Steps to reproduce

1. `ls -l ~/.local/state/fnm_multishells/`
2. `fnm env`
3. `ls -l ~/.local/state/fnm_multishells/` 

See below for an example.

```
~ $ ls -l ~/.local/state/fnm_multishells/
total 0
lrwxrwxrwx  1 simon  staff  60 30 May 19:29 10490_1717093741089@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:52 14195_1717188721723@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:55 16398_1717188910614@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:56 16925_1717188990163@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 10:43 19992_1717234995742@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 12:46 23383_1717242384255@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x@ 1 simon  staff  60  1 Jun 12:48 24361_1717242496374@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:23 25163_1717244639266@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:24 25728_1717244684333@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:25 28648_1717244736014@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:26 29574_1717244776002@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:53 30246_1717253613644@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:54 31054_1717253641952@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:58 34531_1717253933143@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:46 84750_1717321618751@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:54 90600_1717322089278@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:55 91361_1717322149380@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91526_1717322162864@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91753_1717322164755@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:58 93123_1717322312480@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97556_1717322526821@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97788_1717322533986@ -> /Users/simon/Library/Application Support/fnm/aliases/default
~ $ fnm env
set -gx PATH "/Users/simon/.local/state/fnm_multishells/98626_1717322651863/bin" $PATH;
set -gx FNM_NODE_DIST_MIRROR "https://nodejs.org/dist";
set -gx FNM_MULTISHELL_PATH "/Users/simon/.local/state/fnm_multishells/98626_1717322651863";
set -gx FNM_RESOLVE_ENGINES "false";
set -gx FNM_DIR "/Users/simon/Library/Application Support/fnm";
set -gx FNM_ARCH "arm64";
set -gx FNM_VERSION_FILE_STRATEGY "local";
set -gx FNM_LOGLEVEL "info";
set -gx FNM_COREPACK_ENABLED "false";
~ $ ls -l ~/.local/state/fnm_multishells/
total 0
lrwxrwxrwx  1 simon  staff  60 30 May 19:29 10490_1717093741089@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:52 14195_1717188721723@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:55 16398_1717188910614@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:56 16925_1717188990163@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 10:43 19992_1717234995742@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 12:46 23383_1717242384255@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x@ 1 simon  staff  60  1 Jun 12:48 24361_1717242496374@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:23 25163_1717244639266@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:24 25728_1717244684333@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:25 28648_1717244736014@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:26 29574_1717244776002@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:53 30246_1717253613644@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:54 31054_1717253641952@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:58 34531_1717253933143@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:46 84750_1717321618751@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:54 90600_1717322089278@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:55 91361_1717322149380@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91526_1717322162864@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91753_1717322164755@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:58 93123_1717322312480@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97556_1717322526821@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97788_1717322533986@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:04 98626_1717322651863@ -> /Users/simon/Library/Application Support/fnm/aliases/default
~ $ fnm env --shell=zsh
export PATH="/Users/simon/.local/state/fnm_multishells/98912_1717322667474/bin":$PATH
export FNM_MULTISHELL_PATH="/Users/simon/.local/state/fnm_multishells/98912_1717322667474"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_COREPACK_ENABLED="false"
export FNM_RESOLVE_ENGINES="false"
export FNM_DIR="/Users/simon/Library/Application Support/fnm"
export FNM_ARCH="arm64"
rehash
~ $ ls -l ~/.local/state/fnm_multishells/
total 0
lrwxrwxrwx  1 simon  staff  60 30 May 19:29 10490_1717093741089@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:52 14195_1717188721723@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:55 16398_1717188910614@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60 31 May 21:56 16925_1717188990163@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 10:43 19992_1717234995742@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 12:46 23383_1717242384255@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x@ 1 simon  staff  60  1 Jun 12:48 24361_1717242496374@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:23 25163_1717244639266@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:24 25728_1717244684333@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:25 28648_1717244736014@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 13:26 29574_1717244776002@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:53 30246_1717253613644@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:54 31054_1717253641952@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  1 Jun 15:58 34531_1717253933143@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:46 84750_1717321618751@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:54 90600_1717322089278@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:55 91361_1717322149380@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91526_1717322162864@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:56 91753_1717322164755@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 10:58 93123_1717322312480@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97556_1717322526821@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:02 97788_1717322533986@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:04 98626_1717322651863@ -> /Users/simon/Library/Application Support/fnm/aliases/default
lrwxr-xr-x  1 simon  staff  60  2 Jun 11:04 98912_1717322667474@ -> /Users/simon/Library/Application Support/fnm/aliases/default
```

**Comment by Schniz** [comment] 2024-06-02 10:18
this is by design 🙏 symlinks are practically free. I need to write a doc instead of keep responding with the same comment

so basically, `fnm env` is supposed to run in your shell initialization, so it creates a new symlink for that shell. you can feel free to clean up `~/.local/state/fnm_multishells` every now and then, but it'll break all your running shells. it might be okay on reboot though.

the "multishells" are basically a symlink for a given shell, so you can have a session with Node.js 20 and another one with Node.js 18--we don't have a "global fnm symlink", but we have a symlink for each shell session!

fnm used to have a temp directory, but recent changes in macos changed temp directories to sometimes cleanup between hibernations, and not just reboots. so we had to persist the symlinks somewhere else.

If there's any other solution, I'd be happy to know about it. I know some shells have exit hooks, but they don't run if you force-kill them (which most people do anyway when they're closing the tab window or tmux pane instead of `ctrl-d` or `exit` the session)

another thing we can do is to have a `fnm env --pid=$$` and then add a `fnm cleanup` that checks the running pids. I don't think it's a good experience and if you don't look around the multishells directory it shouldn't bother you anyway.

**Comment by simonwhitaker** [comment] 2024-06-02 10:18
OK, so it looks like v1.37.0 introduced the use of the `~/.local/state/fnm_multishells/` directory, whereas on MacOS, v1.36.0 and earlier used ~/Library/Caches/fnm_multishells/. And if I look there I see I have 2653 symlinks in that directory.

Is this expected? Should anything be cleaning those symlinks up?

(I use fish shell and follow [these instructions](https://github.com/Schniz/fnm?tab=readme-ov-file#fish-shell) to initialise fnm, so I'm called `fnm env` every time I start a new shell.)

**Closed by Schniz** 2024-06-02 10:18 UTC

**Comment by simonwhitaker** [comment] 2024-06-02 10:20
> this is by design 🙏 symlinks are practically free. I need to write a doc instead of keep responding with the same comment

Thanks so much for the informative (and quick) reply. 🙏
