### ISSUE TITLE
WSL Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by gilly3** [Schniz/fnm#174] opened 2019-12-05 19:18 UTC
I installed `fnm` onto WSL Ubuntu 18.04, via:

```bash
curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash
```

When I run either `fnm ls-remote` or `fnm install lts/*`, I get:

```
Looking for some node versions upstream...
Illegal instruction (core dumped)
```

**Comment by Schniz** [comment] 2019-12-08 10:20
Is `WSL` === `Windows Subsystem Linux`? Maybe we need to make a build specifically there? Have you tried building from source?

**Comment by vasylherch** [comment] 2019-12-09 10:12
I have the same problem with 1.17.0
But 1.16.0 works perfect in Windows Sybsystem Linux

**Comment by gilly3** [comment] 2019-12-09 15:31
Yes, Windows Subsystem for Linux.  I tried v1.16.0 and had no luck.  I get the same error.  I'll try building from source and let you know how that goes.

**Comment by gilly3** [comment] 2019-12-10 23:19
I finally got it built from source and running successfully on WSL.  It's ironic that step one of building from source is to invoke npm.  So, I was forced to find an alternate way of installing node.  Wanting to avoid nvm, I tried volta, which is apparently much more than what either nvm or fnm are trying to accomplish, and probably led to further headaches.  Volta didn't want to let me globally install esy via npm, but it wasn't bothered when pnpm installed it globally.  But, then it wasn't actually available globally, so I resorted to use pnpx to invoke esy.  Once finally built, I had to invoke it via:

```bash
$ pnpx esy x fnm.exe install lts/*
$ pnpx esy x fnm.exe use v12.13.1
```
At this point, with node and npm now installed outside of volta's realm, I could ditch volta, and reinstall esy, so that I was ultimately able to invoke esy without pnpm:

```bash
$ esy x fnm.exe install lts/*
$ esy x fnm.exe use v12.13.1
```
But, only from the source root directory.  How do I get from here to a fully built binary that I can invoke via `fnm` from any directory?

**Comment by evan-hughes** [comment] 2019-12-16 16:22
I'm seeing similar issues when installing fnm onto an Ubuntu 16.04.6 instance running in Vagrant:

```
$ FNM_LOGLEVEL=debug fnm install v8.10.0
Looking for node v8.10.0 for linux x64
Illegal instruction
```

**Comment by Schniz** [comment] 2019-12-17 07:42
Hey friends, sorry for the late response!

@gilly3 
> How do I get from here to a fully built binary that I can invoke via `fnm` from any directory?

I copy it from `_esy/default/build/default/executable/FnmApp.exe`, pretty verbose isn't it? 😜 


@evan-hughes 
> running in Vagrant

Does it happen out of Vagrant too? I think it relates to the actual hardware, so Vagrant won't be the issue here.

I think this issue should be fixed but I don't have a computer with a CPU that throws this error. It's very odd that 1.16.0 doesn't work, but maybe we need to run build on WSL and not just on Ubuntu? (which sounds very odd)

**Comment by evan-hughes** [comment] 2019-12-17 14:17
> Does it happen out of Vagrant too? I think it relates to the actual hardware, so Vagrant won't be the issue here.

I haven't seen the illegal instruction outside of vagrant, but my org. only runs fnm in a container. 

FWIW, it's inconsistent across hardware. I've seen the illegal instruction error on a selection of macbook pros and linux machines, but it seems to succeed on very similar/same hardware. 

I'm not familiar with the "Illegal Instruction" complaint. Is that from ocaml? If so, is there any debug output we could get that would show more about the error?

**Comment by Schniz** [comment] 2019-12-17 14:19
> FWIW, it's inconsistent across hardware

Yup, this is why I'm trying to fix it in #177. I'd be happy knowing if that works for you :)

**Comment by Schniz** [comment] 2019-12-17 14:20
> I'm not familiar with the "Illegal Instruction" complaint. Is that from ocaml? If so, is there any debug output we could get that would show more about the error?

I think this is a panic from C, but I'm not sure. Seems that libgmp is the cause for this, and it uses Intel `adx` because it is available on CI machines. Using the `--enable-fat` flag should make it select whether to use `adx` or not on runtime

**Comment by Schniz** [comment] 2020-02-25 22:20
Hi, is it fixed in the latest releases?

**Comment by lakinwecker** [comment] 2020-05-02 18:08
I'm seeing it on an Ubuntu 18.04 box

**Comment by Schniz** [comment] 2020-05-03 13:06
> I'm seeing it on an Ubuntu 18.04 box

Hi @lakinwecker, I don't think it's related to your operating system. Please try building fnm on your machine and see if the problem persists. Also, I'd be happy for you to follow the same steps so we'll be able to debug it: https://github.com/Schniz/fnm/issues/173

Unfortunately, I can't really help with these issues — so I'd be happy if you open a PR that fixes it for you and download the artifacts from CI. "Works on my machine" is usually a joke, but in this case, this is the truth. Let me know if I can assist in any way to make it work.

**Comment by lakinwecker** [comment] 2020-05-03 13:50
I fully understand your point! :D This is on a server, so I'll see if I can get it built, I've never built stuff like this, but the instructions looked dead easy. I'll see if I can find the time.  I should probably open another issue though, as this has nothing to do with WSL in my case.

**Comment by Schniz** [comment] 2020-05-04 15:24
I'm closing this issue. For future users: I'm really sorry it doesn't work on your machine. We build fnm on CI machines and we try to make it as cross-platform as it can. Please feel free to open a new issue and let us know which illegal instruction is failing on your machine. We'll probably ask you to open a PR and try to solve it with us (and with the native development channel in Reason Discord) because I can't test it on my machine and it'd be a very slow ping-pong game 😕

**Closed by Schniz** 2020-05-04 15:24 UTC
