### ISSUE TITLE
I found that FRM runs every time  Creates new nodejs content in the C:\Users\*****\AppData\Local\fnm_multishells

### ISSUE THREAD

**Issue by mxm646690173** [Schniz/fnm#1073] opened 2023-12-02 13:42 UTC
Like this
![image](https://github.com/Schniz/fnm/assets/57613270/9cb9f6da-55aa-455e-b7aa-2894efb6dae5)

**Comment by Schniz** [comment] 2023-12-02 14:58
Anyway this is not a bug and it ain't actionable so I'm closing it. Thanks for posting an issue 🙃

**Closed** 2023-12-02 14:59 UTC

**Comment by RoyRao2333** [comment] 2024-03-26 06:52
<img width="542" alt="image" src="https://github.com/Schniz/fnm/assets/31413093/fd55f52d-de8e-4fc5-b512-9e82fae1b41f">

This can be very confusing as I thought `fnm` really installed node into Caches folder...

Maybe you can borrow the idea of shims from `pyenv`. Or, only generate new temp entry when user manually called something like `fnm local 18.19.1` or `fnm shell 18.19.1`. Anyway, as for me, I would like to have correct path returned when I call `which node` in my current using version of node.
