### ISSUE TITLE
svg weird font size

### ISSUE THREAD

**Issue by kamiyaa** [Schniz/fnm#500] opened 2021-07-28 15:35 UTC
I don't think this is how the image should be looking...
Might be something with my setup.

Running on Firefox-90.0.2

![20210728-113317_swappy](https://user-images.githubusercontent.com/8345320/127351911-52e649fe-c541-4e02-b21c-d4f0c5ddc867.png)

**Comment by Schniz** [comment] 2021-07-28 17:42
Feel free to fix it if you know how. This is not a part of the product and I can't reproduce on any of my devices. 

I'm closing this because it's not related to fnm but to the CLI app that generates the svg. But I'm thankful for you filing it 🙏

**Closed by Schniz** 2021-07-28 17:42 UTC

**Comment by kamiyaa** [comment] 2021-07-28 17:43
Yeah no problem! I didn't really expect a fix anyways :+1:

**Comment by connorjs** [comment] 2022-02-17 04:27
I had the same issue. Caused by Firefox + minimum font size, see https://github.com/marionebl/svg-term-cli/issues/39

**Comment by Schniz** [comment] 2022-02-17 09:09
Thanks for the details @connorjs. Appreciate it!
I hope that they'll fix it! 🙏
