### ISSUE TITLE
Broken proxy support since v1.28.0

### ISSUE THREAD

**Issue by lcrockett** [Schniz/fnm#585] opened 2021-11-30 17:01 UTC
There is a discrepancy between v1.27.0 and v1.28.0 that broke proxy support for corporate environments where proxy servers are enforced. Using v1.28.0 prevents users behind proxies from using FNM to download Node release or list remotely available Node versions.

The error that pops up starting with v1.28.0 states `error: HttpError: https://nodejs.org/dist/index.json: Connection Failed: Connect error: Network unreachable (os error 101)`. Using v1.27.0 or below resolves the issue. Upgrading to v1.28.1 does not resolve the issue either.

Perhaps it's related to the replacement of `reqwest` for `ureq` ?

**Comment by Schniz** [comment] 2021-11-30 18:01
Indeed, probably related to #580, I will try to open a PR now, reverting the changes. The problem is--that we had some stylistic changes too so the revert will be manual :)

**Comment by Schniz** [comment] 2021-11-30 19:25
Can you please try the binaries from #586?

**Comment by Schniz** [comment] 2021-12-01 15:09
@lcrockett download the artifact that fits your OS and arch from the build pipeline: https://github.com/Schniz/fnm/actions/runs/1522331110 😃

**Comment by lcrockett** [comment] 2021-12-01 15:39
Works like a charmadillo, cheers !

**Comment by Schniz** [comment] 2021-12-02 19:37
Great! Nice to hear.

**Comment by Schniz** [comment] 2021-12-05 09:23
merged in 3fc1184bcfbe5bcdd5fc062f96a87fcb72f8a25c

**Closed by Schniz** 2021-12-05 09:23 UTC
