### ISSUE TITLE
Xcode is having trouble finding node

### ISSUE THREAD

**Issue by maharjanaman** [Schniz/fnm#475] opened 2021-06-14 09:42 UTC
When I try to build react-native project on xcode, I get
```
env: node: No such file or directory 
Command PhaseScriptExecution failed with a nonzero exit code
```
On shell(zsh), I don't have any trouble with node and `which node` print outs `/var/folders/nz/hh7gg42x1tjf443r4fq3xylm0000gn/T/fnm_multishells/33995_1623643112968/bin/node`.

Is there anything I'm missing during installation process?

**Comment by joeyfigaro** [comment] 2021-06-19 14:54
Having same issue. I tried updating RN to make use of their `find-node.sh` script, but it looks like it's looking for `NODE_BINARY`, which is undefined. Is there a recommended way to keep `NODE_BINARY` pointing to the current version used by fnm?

**Comment by maharjanaman** [comment] 2021-06-19 15:21
@joeyfigaro Was able to run the project by installing another node version using brew i.e. `brew install node`, which then acts as system node.

**Comment by Schniz** [comment] 2021-08-03 12:18
duplicate of #486 (please reopen if I'm getting this wrong)

**Closed by Schniz** 2021-08-03 12:18 UTC

**Comment by douglasjunior** [comment] 2021-08-11 11:22
For `nvm` we can just run `ln -s $(which node) /usr/local/bin/node` to create a link to node binary, but with `fnm` this dont work. 😢

**Comment by Schniz** [comment] 2021-08-11 12:34
You can run `ln -s "$(realpath $(which node))" /usr/local/bin/node`, but I am not sure I would suggest so.

Example:
```sh-session
$ echo "$(realpath $(which node))"
/Users/<username>/.fnm/node-versions/v14.15.4/installation/bin/node
```

**Comment by douglasjunior** [comment] 2021-08-11 14:29
Thanks @Schniz this looks good.

And about `husky js`, any suggestions?

I tried to add `export PATH=$HOME/.fnm:$PATH` to the `~/.huskyrc`, but don't work.

**Comment by taylorkline** [comment] 2024-05-03 18:47
I thought about having an `.xcode.local` with:

```
export NODE_BINARY=/System/Volumes/Data/Users/username/Library/Application Support/fnm/aliases/lts-hydrogen/bin/node
```

This does not work due to the space in `"Application Support"` (even if escaped!)

However, a symlink `ln -s /System/Volumes/Data/Users/username/Library/Application\ Support/fnm/aliases/lts-hydrogen/bin/node ~/node-18` allows for:

```
export NODE_BINARY=/Users/username/node-18
```

To work just fine.

**Comment by kud** [comment] 2024-05-30 11:39
I've also got this issue with react-native.

For instance, the `.xcode.env` file is:

```
# This `.xcode.env` file is versioned and is used to source the environment
# used when running script phases inside Xcode.
# To customize your local environment, you can create an `.xcode.env.local`
# file that is not versioned.

# NODE_BINARY variable contains the PATH to the node executable.
#
# Customize the NODE_BINARY variable here.
# For example, to use nvm with brew, add the following line
# . "$(brew --prefix nvm)/nvm.sh" --no-use
export NODE_BINARY=$(command -v node)
```

and my `.xcode.env.local` is:

```
export NODE_BINARY=/var/folders/07/scm1dt7n1sz2tk39cqfhvs7w0000gq/T/yarn--1717000088176-0.6543025354301102/node
```

so everytime I reboot my computer, it does not work anymore.

What I usually do is to remove the `.xcode.env.local` first and start the react-native command, and it works. But I would like to adjust for once `.xcode.env.local` instead of removing it everytime.

I would like to understand the difference between `$(realpath $(which node))` and `$(command -v node)` it does not provide the same path:

```
echo "$(realpath $(which node))"
/Users/mest001/Library/Application Support/fnm/node-versions/v20.11.1/installation/bin/node
```

```
echo "$(command -v node)"
/Users/mest001/Library/Caches/fnm_multishells/6417_1717061860945/bin/node
```

What's the best?

Thanks.

**Comment by kud** [comment] 2024-05-30 11:45
I've tried that in my `.xcode.env.local`:

```
export NODE_BINARY=$(realpath $(which node))
```

Let me know if it's the best option.

**Comment by erkie** [comment] 2025-02-20 21:15
I added this to the `ios/.xcode.env` file (I wanted to be able to check in the env file so it wanted it to work in an environment without fnm as well). For some reason it wasn't sourcing the proper profile scripts so had to add that manually. 🤷 


```shell
# No node? Try to load via fnm
if ! command -v node &> /dev/null; then
  output=$(zsh -l -c 'source ~/.profile; source ~/.zshrc; eval "$(fnm env --shell=zsh)" && fnm env')
  eval "$output"

  # if no node is found throw an error
  if ! command -v node &> /dev/null; then
      echo "Node could not be found: $SHELL $USER $HOME"
      exit 1
  fi
fi

export NODE_BINARY=$(realpath $(which node))
```
