### ISSUE TITLE
.nvmrc version match fail

### ISSUE THREAD

**Issue by daniellwdb** [Schniz/fnm#794] opened 2022-08-07 08:34 UTC
`.nvmrc`:
```
>=16.9
```
`.zshrc`:
```bash
export PATH=/home/daniell/.fnm:$PATH
eval "$(fnm env --use-on-cd)"
```
`Terminal output`:
```bash
→ source ~/.zshrc                                                                           
Can't find an installed Node version matching >=16.9.

→ fnm use 16
Using Node v16.16.0
```

**Comment by Schniz** [comment] 2022-08-07 08:43
this syntax is not supported right now

**Comment by Schniz** [comment] 2022-08-07 08:43
is it supported by nvm?

**Comment by daniellwdb** [comment] 2022-08-07 09:06
Apparently it isn't, should have checked first. Is the aim to be 1:1 or could this possibly be supported? Maybe there is an alternative syntax I'm not aware off

**Comment by Schniz** [comment] 2022-08-07 09:07
I want to support this syntax because I want to support `engines` in the future as it fits the standard better. Even if we implement this, I think that `.nvmrc` should be compatible with nvm so it won't be supported, maybe on `.node-version` which has no real standards AFAIK

**Comment by Schniz** [comment] 2022-08-07 09:14
anyway I'm gonna close this issue as it's not a bug. We can create an issue to support [VersionReq](https://docs.rs/semver/latest/semver/struct.VersionReq.html) in `engines` 😁 🙏 

lmk if you want me to reopen this. thanks for the filing the issue btw @daniellwdb! :pray:

**Closed by Schniz** 2022-08-07 09:14 UTC
