### ISSUE TITLE
fnm not respecting/using shell proxy environment variables

### ISSUE THREAD

**Issue by hisea** [Schniz/fnm#214] opened 2020-04-20 15:30 UTC
I'm using fnm behind a corporate proxy.

I have proxy settings in my .zshrc file setup uing

```
export http_proxy=http://<proxy>
export HTTP_PROXY=http://<proxy>
export https_proxy=http://<proxy>
export HTTPS_PROXY=http://<proxy>
export ftp_proxy=http://<proxy>
export rsync_proxy=http://<proxy>
export ALL_PROXY=http://<proxy>
```

but still when running fnm it complains not able to connect to node mirror.

```
$ fnm ls-remote
Looking for some node versions upstream...
fnm: internal error, uncaught exception:
     (Failure
       "TLS to non-TCP currently unsupported: host=nodejs.org endp=(Unknown \"name resolution failed\")")
```

**Comment by Schniz** [comment] 2020-04-21 18:45
Looks about right. Sorry about that.

Maybe it'll make us replace Cohttp: @sgrove has this issue since 2016: https://github.com/mirage/ocaml-cohttp/issues/515

The good thing: we only use `Cohttp` in the `Http.re` module. Should be not hard to replace.

**Comment by hisea** [comment] 2020-04-22 04:40
Thanks for the great work on such an awesome tool.

Is there a library you recommend to replace?

I'm new to reason but maybe I can take a stab at replacing it.

**Comment by philtim** [comment] 2020-10-22 06:53
Hi. First of all: thanks for this great project which makes life in terms of node so much more pleasant!

Is there any news regarding the possibility to use fnm behind a proxy?

**Comment by Schniz** [comment] 2020-10-22 06:58
Thanks @philtim!

> Is there any news regarding the possibility to use fnm behind a proxy?

Looks like reqwest (the http client for the Rust release) [supports `http_proxy` environment variables](https://github.com/seanmonstar/reqwest/blob/master/tests/proxy.rs#L124)

I will try to release it this weekend as a stable version. You can try [download the pre-release here](https://github.com/Schniz/fnm/releases/tag/v1.22.0-beta-1) and let me know if it actually works 😄

**Comment by philtim** [comment] 2020-10-22 07:07
I've switched to the linux binary version 1.22.0. Proxys are being set and verified to work (e.g. wget, curl) but with `fnm ls-remote` I am getting this error:

`error: HttpError: error sending request for url (https://nodejs.org/dist/index.json): error trying to connect: dns error: failed to lookup address information: Name does not resolve`

**Comment by Schniz** [comment] 2020-10-22 08:14
Do you know a free proxy I can use to test it? Or how can I write a failing test?

**Comment by philtim** [comment] 2020-10-22 08:16
Sadly not, I am behind a corporate proxy.

**Comment by Schniz** [comment] 2020-10-22 08:55
Does it set up with HTTPS_PROXY too?
https://docs.rs/reqwest/0.10.8/reqwest/#proxies
🤔

**Comment by philtim** [comment] 2020-10-22 11:34
Japp, I am setting http_proxy and https_proxy to no avail. To check if there's an issue with my machine, I tried Volta as they also used reqwest (but now switched back to attohtpc as it supports proxies while having a smaller binary size). Volta works if I am setting the proxy, but doesn't work if I unset it. Not sure if this information somehow helps.
Oh, and even if Volta is working on my machine, I'd still prefer fnm 😄

**Comment by Schniz** [comment] 2020-10-22 12:40
looks like `https_proxy` works for me. 🤔 
I mean, it fails because of a bad proxy so I guess it should work?

```
✡ fnm ◦ env https_proxy=https://how-about-no fnm ls-remote
error: HttpError: error sending request for url (https://nodejs.org/dist/index.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

**Comment by philtim** [comment] 2020-10-22 18:51
Not so sure if this is the correct "falsy test". If I do the same steps on my Mac without the corporate proxy, I get the same behaviour as you do. On the windows machine, which has to use the corporate proxy, I always get the same error which implies that the proxy is wrong. I'd assume that something is wrong with either the proxy or my machine, but other utilities like curl or wget do work if I set the env proxy correctly and don't work if I set a false proxy.

Tomorrow I'll try to create an isolated app which is using reqwest and see if I can reproduce the same behaviour. Sorry for bugging you with this edge case.

**Comment by Schniz** [comment] 2020-10-22 19:37
Don't be sorry! I am sorry for not knowing how to solve that. We're both trying to make everything better so I guess it's all for the best. I'd be happy to do whatever I can to make it work for you and everyone that is using a proxy.

**Comment by philtim** [comment] 2020-10-23 09:38
@Schniz I think I was able to narrow it down. I have created a super simple app to query an api and print out the header (it's my very first time to do anything in Rust 🙈 ). Here's the code:

```
use reqwest::ClientBuilder;
use reqwest::Result;

#[tokio::main]
async fn main() -> Result<()> {
    let request_url = format!("https://fakestoreapi.com/products/1");
    println!("{}", request_url);

    let client = ClientBuilder::new().build()?;
    let response = client.head(&request_url).send().await?;

    println!("{:#?}", response);

    Ok(())
}
```

Executing this `proxy-test` app will throw an error as expected. Executing the command `env https_proxy="proxy url as string" proxy-test` does return a positive result. If the proxy is not surrounded by `"`, it will throw the same error.

I've tried to run `env https_proxy="proxy url as string" fnm ls-remote` and it threw the same error. My next try - after a short vacation - will be trying to set the proxy URL directly in the source code. Just to see if for whatever reason the env variable doesn't get picked up. Basically I mean something like this:

`
let client = ClientBuilder::new()
        .proxy(reqwest::Proxy::https("http://url:port")?)
        .build()?;
`

**Comment by hisea** [comment] 2020-10-27 01:19
I can confirm that it's working in my environment with our corp proxy:

```
 21:14:09 ❯ source ~/scripts/set_proxy_https.sh
~
 21:14:11 ❯ fnm --version
fnm 1.22.3
~
 21:14:15 ❯ fnm ls-remote
v0.1.14
v0.1.15
...
```

and in my proxy file:

```

export http_proxy=http://my.corporate.proxy.com:8080
export HTTP_PROXY=$http_proxy
export https_proxy=$http_proxy
export HTTPS_PROXY=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export ALL_PROXY=$http_proxy
export no_proxy="127.0.0.1,localhost,*.local,169.254/16,.my-coprate.domain"
```

**Comment by Schniz** [comment] 2020-10-27 07:41
a-ha! but I did nothing 🤔 
So.. should we close it?

**Comment by philtim** [comment] 2020-10-27 09:01
Yes, please close this issue. I'd call that an issue with the super strict setup my client uses and might be related to wsl/windows and their corporate proxy.

**Comment by Schniz** [comment] 2020-10-27 09:03
Thanks for letting me know 😄 
If you do find a way to fix that, I'd be happy to know. Thanks again!

**Closed by Schniz** 2020-10-27 09:03 UTC

**Comment by philtim** [comment] 2020-10-27 11:55
Just for the record: it is indeed an issue with WSL and happens to be a "hiccup" with DNS. It's super strange, because with other cli's, which also requires a proxy, everything is working. However, this [post ](https://github.com/microsoft/WSL/issues/1350)had a fix for me and I can confirm, too, that fnm is working behind a corporate proxy 👍🏼 Again, thanks for your great work!
